# Generated by Django 5.2.7 on 2026-01-17 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize_trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizetriprequest',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
