# Generated by Django 5.2.7 on 2026-01-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='accounts_em_email_c46531_idx',
            old_name='accounts_em_email_8b3f0c_idx',
        ),
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='accounts_em_expires_2be763_idx',
            old_name='accounts_em_expires_7b1ac9_idx',
        ),
    ]
