# Generated by Django 5.2.7 on 2026-01-08 12:56

import blog.blog.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True, validators=[django.core.validators.RegexValidator(message="Slug must be lowercase letters/numbers with hyphens (e.g. 'langtang-valley-trek').", regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('role', models.CharField(blank=True, max_length=160)),
                ('avatar_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_author_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('type', models.CharField(choices=[('blog', 'Blog'), ('page', 'Page'), ('vlog', 'Vlog')], default='blog', max_length=20)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('guide', 'Guide'), ('news', 'News')], default='article', max_length=20)),
                ('language', models.CharField(db_index=True, default='en', max_length=10)),
                ('slug', models.SlugField(max_length=255, validators=[django.core.validators.RegexValidator(message="Slug must be lowercase letters/numbers with hyphens (e.g. 'langtang-valley-trek').", regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('title', models.CharField(max_length=220)),
                ('subtitle', models.CharField(blank=True, max_length=260)),
                ('meta_title', models.CharField(blank=True, max_length=220)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('description', models.TextField(blank=True)),
                ('excerpt', models.CharField(blank=True, max_length=400)),
                ('publish_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('read_time', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)])),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Challenging', 'Challenging')], default='Moderate', max_length=20)),
                ('canonical_url', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('featured_image', models.JSONField(blank=True, default=blog.blog.models.default_featured_image)),
                ('images', models.JSONField(blank=True, default=blog.blog.models.default_images)),
                ('taxonomies', models.JSONField(blank=True, default=blog.blog.models.default_taxonomies)),
                ('content_settings', models.JSONField(blank=True, default=blog.blog.models.default_content_settings)),
                ('toc', models.JSONField(blank=True, default=blog.blog.models.default_toc)),
                ('content', models.JSONField(blank=True, default=blog.blog.models.default_content)),
                ('cta', models.JSONField(blank=True, default=blog.blog.models.default_cta)),
                ('links', models.JSONField(blank=True, default=blog.blog.models.default_links)),
                ('related_posts', models.JSONField(blank=True, default=blog.blog.models.default_related_posts)),
                ('seo', models.JSONField(blank=True, default=blog.blog.models.default_seo)),
                ('schema', models.JSONField(blank=True, default=blog.blog.models.default_schema)),
                ('social', models.JSONField(blank=True, default=blog.blog.models.default_social)),
                ('editorial', models.JSONField(blank=True, default=blog.blog.models.default_editorial)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('shares', models.PositiveBigIntegerField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('is_liked', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.author')),
            ],
            options={
                'ordering': ['-publish_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_slug', models.SlugField(max_length=255, validators=[django.core.validators.RegexValidator(message="Slug must be lowercase letters/numbers with hyphens (e.g. 'langtang-valley-trek').", regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('new_slug', models.SlugField(max_length=255, validators=[django.core.validators.RegexValidator(message="Slug must be lowercase letters/numbers with hyphens (e.g. 'langtang-valley-trek').", regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('redirect_count', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='blog.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True, validators=[django.core.validators.RegexValidator(message="Slug must be lowercase letters/numbers with hyphens (e.g. 'langtang-valley-trek').", regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='blog_catego_slug_fc0bb9_idx'), models.Index(fields=['is_active', 'order'], name='blog_catego_is_acti_2c46c2_idx')],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True, validators=[django.core.validators.RegexValidator(message="Slug must be lowercase letters/numbers with hyphens (e.g. 'langtang-valley-trek').", regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='blog_region_slug_0924b3_idx'), models.Index(fields=['is_active', 'order'], name='blog_region_is_acti_d88f55_idx')],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.region'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['slug'], name='blog_author_slug_5b1b82_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='blog_author_name_829872_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostslughistory',
            index=models.Index(fields=['old_slug'], name='blog_blogpo_old_slu_a8e051_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostslughistory',
            index=models.Index(fields=['new_slug'], name='blog_blogpo_new_slu_ac80d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blogpostslughistory',
            unique_together={('post', 'old_slug', 'new_slug')},
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'publish_date'], name='blog_blogpo_status_14c682_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['type', 'content_type'], name='blog_blogpo_type_825b78_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured', 'publish_date'], name='blog_blogpo_is_feat_d05540_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.UniqueConstraint(fields=('slug', 'language'), name='uniq_blogpost_slug_language'),
        ),
    ]
