# Generated by Django 5.1.6 on 2026-02-11 10:30

import Evertrek_Nepal.image_validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_description_blogpost_featured_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_alt',
            field=models.CharField(blank=True, default='', help_text='Alt text for the featured hero image (required for accessibility).', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_caption',
            field=models.CharField(blank=True, default='', help_text='Optional caption displayed with the hero image.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_credit',
            field=models.CharField(blank=True, default='', help_text='Optional credit/source for the featured hero image.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='Alt text for the thumbnail/card image (recommended).', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='blog/featured/', validators=[Evertrek_Nepal.image_validators.ImageFileValidator(max_mb=5)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/', validators=[Evertrek_Nepal.image_validators.ImageFileValidator(max_mb=4)]),
        ),
        migrations.CreateModel(
            name='BlogInlineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='blog/inline/', validators=[Evertrek_Nepal.image_validators.ImageFileValidator(max_mb=3)])),
                ('alt_text', models.CharField(help_text='Alt text (required) for inline images.', max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('block_id', models.CharField(blank=True, help_text='Optional content block or section identifier.', max_length=140)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_images', to='blog.blogpost')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
