from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("short_description", models.TextField(blank=True)),
                ("long_description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("duration", models.CharField(blank=True, max_length=50)),
                ("group_size", models.PositiveIntegerField(blank=True, null=True)),
                ("difficulty", models.CharField(blank=True, max_length=80)),
                ("start_point", models.CharField(blank=True, max_length=120)),
                ("max_altitude", models.CharField(blank=True, max_length=50)),
                ("activity", models.CharField(blank=True, max_length=120)),
                ("travel_style", models.CharField(blank=True, max_length=80)),
                ("badge", models.CharField(blank=True, max_length=80)),
                ("rating", models.FloatField(blank=True, default=0.0)),
                ("reviews_count", models.PositiveIntegerField(blank=True, default=0)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("old_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("base_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("original_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("highlights", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TourOverview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(blank=True, max_length=255)),
                ("paragraphs", models.JSONField(blank=True, default=list)),
                ("points", models.JSONField(blank=True, default=list)),
                ("tour", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="overview", to="tours.tour")),
            ],
        ),
        migrations.CreateModel(
            name="TourItineraryDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("duration", models.CharField(blank=True, max_length=50)),
                ("distance", models.CharField(blank=True, max_length=50)),
                ("meals", models.CharField(blank=True, max_length=255)),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itinerary_days", to="tours.tour")),
            ],
            options={"ordering": ["day"], "unique_together": {("tour", "day")}},
        ),
        migrations.CreateModel(
            name="TourHighlight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="highlight_items", to="tours.tour")),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="TourCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inclusions", models.JSONField(blank=True, default=list)),
                ("exclusions", models.JSONField(blank=True, default=list)),
                ("tour", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="cost", to="tours.tour")),
            ],
        ),
        migrations.CreateModel(
            name="TourAdditionalInfoSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("articles", models.JSONField(blank=True, default=list)),
                ("bullets", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="additional_info_sections", to="tours.tour")),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="TourGroupPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, max_length=120)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_size", models.PositiveIntegerField(blank=True, null=True)),
                ("max_size", models.PositiveIntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="group_prices", to="tours.tour")),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="TourGalleryImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_url", models.URLField()),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gallery_images", to="tours.tour")),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="TourSEO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.JSONField(blank=True, default=list)),
                ("canonical_url", models.URLField(blank=True)),
                ("focus_keyword", models.CharField(blank=True, max_length=120)),
                ("og_title", models.CharField(blank=True, max_length=255)),
                ("og_description", models.TextField(blank=True)),
                ("og_image_url", models.URLField(blank=True)),
                ("twitter_title", models.CharField(blank=True, max_length=255)),
                ("twitter_description", models.TextField(blank=True)),
                ("twitter_image_url", models.URLField(blank=True)),
                ("robots_noindex", models.BooleanField(default=False)),
                ("robots_nofollow", models.BooleanField(default=False)),
                ("breadcrumbs", models.JSONField(blank=True, default=list)),
                ("structured_data", models.JSONField(blank=True, default=dict)),
                ("tour", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="seo", to="tours.tour")),
            ],
        ),
        migrations.CreateModel(
            name="TourInternalLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("section", models.CharField(blank=True, max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="internal_links", to="tours.tour")),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="TourBacklink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField()),
                ("anchor_text", models.CharField(blank=True, max_length=255)),
                ("rel", models.CharField(blank=True, max_length=50)),
                ("discovered_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="backlinks", to="tours.tour")),
            ],
        ),
        migrations.CreateModel(
            name="SimilarTour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("related_tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="similar_to", to="tours.tour")),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="similar_tours", to="tours.tour")),
            ],
            options={"ordering": ["order"], "unique_together": {("tour", "related_tour")}},
        ),
        migrations.CreateModel(
            name="TourReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author_name", models.CharField(max_length=120)),
                ("rating", models.PositiveIntegerField(default=5)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("source_name", models.CharField(blank=True, max_length=120)),
                ("source_url", models.URLField(blank=True)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="tours.tour")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
