# Generated by Django 5.1.6 on 2026-01-15 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        ('travel_styles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='primary_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_tours', to='travel_styles.travelstyle'),
        ),
        migrations.AddField(
            model_name='tour',
            name='travel_styles',
            field=models.ManyToManyField(blank=True, related_name='tours', to='travel_styles.travelstyle'),
        ),
    ]
