# Generated by Django 5.1.6 on 2026-02-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_travel_style_collections_pivot'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeaturedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear earlier in the featured list')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show the featured card without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.OneToOneField(help_text='Link an existing tour to this featured slot', on_delete=django.db.models.deletion.CASCADE, related_name='home_featured_entry', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Home featured tour',
                'verbose_name_plural': 'Home featured tours',
                'ordering': ['order', '-tour__rating', '-tour__reviews_count'],
            },
        ),
    ]
