# Generated by Django 5.1.6 on 2026-02-04 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrekCard', '0006_homebesttrek'),
        ('tours', '0004_homefeaturedtour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homefeaturedtour',
            options={'ordering': ['order', '-tour__rating', '-tour__reviews_count'], 'verbose_name': 'Home featured trip', 'verbose_name_plural': 'Home featured trips'},
        ),
        migrations.AddField(
            model_name='homefeaturedtour',
            name='trek',
            field=models.OneToOneField(blank=True, help_text='Link a trek to this featured slot (leave empty when featuring a tour)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_featured_entry', to='TrekCard.trekinfo'),
        ),
        migrations.AlterField(
            model_name='homefeaturedtour',
            name='tour',
            field=models.OneToOneField(blank=True, help_text='Link an existing tour to this featured slot (leave empty when featuring a trek)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_featured_entry', to='tours.tour'),
        ),
        migrations.AddConstraint(
            model_name='homefeaturedtour',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tour__isnull', False), ('trek__isnull', True)), models.Q(('tour__isnull', True), ('trek__isnull', False)), _connector='OR'), name='home_featured_content_type_present'),
        ),
    ]
