# Generated by Django 5.1.6 on 2026-02-11 10:43

import Evertrek_Nepal.image_validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_homefeaturedtour_options_homefeaturedtour_trek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='Alt text for the listing/card image (recommended).', max_length=255),
        ),
        migrations.AddField(
            model_name='tour',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='tour/cards/', validators=[Evertrek_Nepal.image_validators.ImageFileValidator(max_mb=4)]),
        ),
        migrations.AddField(
            model_name='tourgalleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour/gallery/', validators=[Evertrek_Nepal.image_validators.ImageFileValidator(max_mb=3)]),
        ),
        migrations.AlterField(
            model_name='tourgalleryimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Alt text for gallery image (recommended).', max_length=255),
        ),
        migrations.AlterField(
            model_name='tourgalleryimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tourgalleryimage',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='TourHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour/hero/', validators=[Evertrek_Nepal.image_validators.ImageFileValidator(max_mb=5)])),
                ('image_url', models.URLField(blank=True, default='')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Alt text for the hero image (required for accessibility).', max_length=255)),
                ('caption', models.CharField(blank=True, default='', help_text='Optional caption for the hero image.', max_length=255)),
                ('credit', models.CharField(blank=True, default='', help_text='Optional credit/source for the hero image.', max_length=255)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_image', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Hero Image',
                'verbose_name_plural': 'Tour Hero Images',
            },
        ),
    ]
