# Generated by Django 5.1.6 on 2025-10-17 13:34

import TrekCard.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrekAdditionalInfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('articles', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrekBookingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pricing_mode', models.CharField(choices=[('base_only', 'Only Base Price'), ('original_and_save', 'Show Original Price with Saving %'), ('original_only', 'Show Only Original Price')], default='base_only', max_length=20)),
                ('badge_label', models.CharField(blank=True, max_length=100, null=True)),
                ('secure_payment', models.BooleanField(default=False)),
                ('no_hidden_fees', models.BooleanField(default=False)),
                ('free_cancellation', models.BooleanField(default=False)),
                ('support_24_7', models.BooleanField(default=False)),
                ('trusted_reviews', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrekElevationChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Elevation Chart', max_length=128)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='elevation_chart/')),
            ],
        ),
        migrations.CreateModel(
            name='TrekFAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('icon', models.CharField(choices=[('general', 'General Information'), ('practical', 'Accommodation & Meals'), ('booking', 'Booking'), ('financial', 'Financial'), ('eligibility', 'Eligibility'), ('health', 'Safety & Health'), ('gear', 'Equipment & Gear')], default='general', max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrekInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('duration', models.CharField(help_text="Human text, e.g. '14 Days'", max_length=50)),
                ('trip_grade', models.CharField(max_length=50)),
                ('start_point', models.CharField(max_length=100)),
                ('group_size', models.CharField(max_length=50)),
                ('max_altitude', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=100)),
                ('rating', models.FloatField(blank=True, default=0.0)),
                ('reviews', models.PositiveIntegerField(blank=True, default=0)),
                ('review_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trek',
                'verbose_name_plural': 'Treks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrekAdditionalInfoBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='TrekCard.trekadditionalinfosection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrekBookingGroupPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_size', models.PositiveIntegerField(blank=True, help_text='Minimum group size', null=True)),
                ('max_size', models.PositiveIntegerField(blank=True, help_text='Maximum group size', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_prices', to='TrekCard.trekbookingcard')),
            ],
            options={
                'ordering': ['min_size'],
            },
        ),
        migrations.CreateModel(
            name='TrekElevationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(help_text='Day number')),
                ('title', models.CharField(max_length=128)),
                ('elevation', models.PositiveIntegerField(help_text='Meters')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='TrekCard.trekelevationchart')),
            ],
            options={
                'ordering': ['order', 'day'],
            },
        ),
        migrations.CreateModel(
            name='TrekFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='TrekCard.trekfaqcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrekHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('culture', 'Culture'), ('scenery', 'Scenery'), ('achievement', 'Achievement'), ('photography', 'Photography'), ('community', 'Community'), ('health', 'Health')], max_length=20)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='TrekCard.trekinfo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrekHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Main title', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle/tagline', max_length=512)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('season', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('cta_label', models.CharField(default='Book This Trek', max_length=100)),
                ('cta_link', models.CharField(blank=True, max_length=256)),
                ('trek', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_section', to='TrekCard.trekinfo')),
            ],
            options={
                'verbose_name': 'Trek Hero Section',
                'verbose_name_plural': 'Trek Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='TrekGroupPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_prices', to='TrekCard.trekinfo')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='TrekGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trek_gallery/')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('caption', models.CharField(blank=True, max_length=256)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='TrekCard.trekinfo')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='trekfaqcategory',
            name='trek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_categories', to='TrekCard.trekinfo'),
        ),
        migrations.AddField(
            model_name='trekelevationchart',
            name='trek',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elevation_chart', to='TrekCard.trekinfo'),
        ),
        migrations.CreateModel(
            name='TrekDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(choices=[('Guaranteed', 'Guaranteed'), ('Available', 'Available'), ('Sold Out', 'Sold Out'), ('Limited', 'Limited')], default='Guaranteed', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seats_left', models.PositiveIntegerField(default=0)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='TrekCard.trekinfo')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='TrekDateHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(max_length=256)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_highlights', to='TrekCard.trekinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TrekCostAndDateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(default='Start Dates refer to your arrival date in Nepal. End Dates correspond to your return date from Nepal.')),
                ('trek', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_and_date_section', to='TrekCard.trekinfo')),
            ],
        ),
        migrations.AddField(
            model_name='trekbookingcard',
            name='trek',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_card', to='TrekCard.trekinfo'),
        ),
        migrations.AddField(
            model_name='trekadditionalinfosection',
            name='trek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info_sections', to='TrekCard.trekinfo'),
        ),
        migrations.CreateModel(
            name='TrekAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='trek_pdfs/')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='trek_maps/')),
                ('trek', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='TrekCard.trekinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cost_inclusions', models.JSONField(blank=True, default=list)),
                ('cost_exclusions', models.JSONField(blank=True, default=list)),
                ('trek', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='TrekCard.trekinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BookingIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('price_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('held', 'Held (awaiting payment)'), ('expired', 'Expired'), ('confirmed', 'Confirmed')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=TrekCard.models.default_booking_expiry)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TrekCard.trekdeparture')),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_intents', to='TrekCard.trekinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TrekOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trek', models.OneToOneField(help_text='The trek this overview belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='TrekCard.trekinfo')),
            ],
            options={
                'verbose_name': 'Trek Overview',
                'verbose_name_plural': 'Trek Overviews',
            },
        ),
        migrations.CreateModel(
            name='TrekOverviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('articles', models.JSONField(default=list, help_text='List of paragraph strings')),
                ('order', models.PositiveIntegerField(default=0)),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='TrekCard.trekoverview')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrekOverviewBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='TrekCard.trekoverviewsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrekReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=128)),
                ('reviewer_country', models.CharField(blank=True, max_length=64)),
                ('reviewer_avatar', models.ImageField(blank=True, null=True, upload_to='review_avatars/')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1–5 stars')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('tripadvisor', 'TripAdvisor'), ('google', 'Google'), ('other', 'Other')], default='internal', max_length=24)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_list', to='TrekCard.trekinfo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarTrek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('related_trek', models.ForeignKey(help_text='A trek that is similar or recommended.', on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='TrekCard.trekinfo')),
                ('trek', models.ForeignKey(help_text='The trek for which similar treks are suggested.', on_delete=django.db.models.deletion.CASCADE, related_name='similar_treks', to='TrekCard.trekinfo')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('trek', 'related_trek')},
            },
        ),
        migrations.CreateModel(
            name='TrekItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('accommodation', models.CharField(blank=True, max_length=255, null=True)),
                ('altitude', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('meals', models.CharField(blank=True, max_length=255, null=True)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='TrekCard.trekinfo')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('trek', 'day')},
            },
        ),
    ]
