# Generated by Django 5.1.6 on 2025-10-18 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrekCard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_label', models.CharField(blank=True, help_text="Optional short tag line, e.g. 'EBC, Gokyo, Three Passes'", max_length=40)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order in menus/lists')),
                ('marker_x', models.PositiveIntegerField(default=50, help_text='Marker % from the left (0–100)')),
                ('marker_y', models.PositiveIntegerField(default=50, help_text='Marker % from the top (0–100)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='region_covers/')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='trekinfo',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='trekinfo',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Select the region this trek belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treks', to='TrekCard.region'),
        ),
    ]
