# Generated by Django 5.2.7 on 2025-12-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrekCard', '0002_region_alter_trekinfo_duration_trekinfo_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekitineraryday',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trekitineraryday',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trekitineraryday',
            name='place_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
