# Generated by Django 5.1.6 on 2026-01-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrekCard', '0004_booking_intent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekaction',
            name='route_geojson',
            field=models.FileField(blank=True, null=True, upload_to='trek_routes/'),
        ),
    ]
