# Generated by Django 5.1.6 on 2026-02-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrekCard', '0005_trekaction_route_geojson'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBestTrek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear earlier in the Best Treks grid.')),
                ('is_active', models.BooleanField(default=True, help_text='Keep this slot active on the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trek', models.OneToOneField(help_text='Select the trek to showcase under Best Treks in Nepal.', on_delete=django.db.models.deletion.CASCADE, related_name='home_best_entry', to='TrekCard.trekinfo')),
            ],
            options={
                'verbose_name': 'Home best trek',
                'verbose_name_plural': 'Home best treks',
                'ordering': ['order', '-trek__rating', '-trek__reviews'],
            },
        ),
    ]
