# Generated by Django 5.1.6 on 2026-02-11 10:30

import Evertrek_Nepal.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrekCard', '0006_homebesttrek'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekgalleryimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Alt text (recommended) for accessibility and SEO.', max_length=256),
        ),
        migrations.AddField(
            model_name='trekherosection',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='Alt text for the hero image (SEO/accessibility).', max_length=256),
        ),
        migrations.AddField(
            model_name='trekherosection',
            name='image_caption',
            field=models.CharField(blank=True, default='', help_text='Optional caption shown with the hero image.', max_length=256),
        ),
        migrations.AlterField(
            model_name='trekgalleryimage',
            name='image',
            field=models.ImageField(upload_to='trek_gallery/', validators=[Evertrek_Nepal.image_validators.ImageFileValidator(max_mb=3)]),
        ),
        migrations.AlterField(
            model_name='trekherosection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/', validators=[Evertrek_Nepal.image_validators.ImageFileValidator(max_mb=5)]),
        ),
    ]
