# Generated by Django 5.2.7 on 2026-01-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_styles', '0002_travel_style_tour'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='travelstyletour',
            new_name='travel_styl_travel__737b12_idx',
            old_name='travelstyle_order_idx',
        ),
        migrations.RenameIndex(
            model_name='travelstyletour',
            new_name='travel_styl_travel__9aec59_idx',
            old_name='travelstyle_featured_order_idx',
        ),
    ]
