# Generated by Django 5.1.6 on 2026-01-10 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_title', models.CharField(blank=True, max_length=16)),
                ('lead_first_name', models.CharField(blank=True, max_length=64)),
                ('lead_last_name', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('emergency_contact', models.CharField(blank=True, max_length=256)),
                ('dietary_requirements', models.CharField(blank=True, max_length=256)),
                ('medical_conditions', models.CharField(blank=True, max_length=256)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=24)),
                ('guide_language', models.CharField(blank=True, max_length=64)),
                ('special_requests', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_details', to='bookings.booking')),
            ],
        ),
    ]
