# Generated by Django 5.2.7 on 2026-01-10 07:25

import bookings.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_total_amount_alter_bookingreceipt_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookingreceipt',
            name='pdf',
            field=models.FileField(upload_to=bookings.models.receipt_upload_path),
        ),
    ]
